#! /usr/bin/env bash
set -euo pipefail

script_dir="$(dirname "${BASH_SOURCE[0]}")"
cd $script_dir/..

echo "Generating .rei files..."
echo "If this doesn't work, make sure to kill any other concurrently running compilation processes (e.g. watch commands, reason language servers, etc.)"
for cmi_file_path in $(find ./lib/bs/src -name '*.cmi' | grep 'Relude_Array.cmi\|Relude_List.cmi')
do
  #echo $cmi_file_path
  rei_file_path=$(echo $cmi_file_path | sed 's/lib\/bs\///' | sed 's/\.cmi$/.rei/')
  #echo $rei_file_path

  command="./node_modules/.bin/bsc -bs-re-out ${cmi_file_path} > ${rei_file_path}"
  echo $command
  eval $command
done