#! /usr/bin/env bash
set -euo pipefail

script_dir="$(dirname "${BASH_SOURCE[0]}")"
cd $script_dir/..

echo "Removing .rei files..."
for rei_file_path in $(find ./src -name '*.rei')
do
  command="rm $rei_file_path"
  echo $command
  eval $command
done